BaoCaoCuoiKi/Project/BaoCao/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BaoCao.Models
{
    public class Post
    {
        [Key]
        public int ID { get; set; }
        public string Title { get; set; }
        [Display(Name = "Nội dung")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string Body { get; set; }
        [Display(Name = "Ngày tạo")]
        public DateTime DateCreated { get; set; }
        [Display(Name = "Ngày cập nhật")]
        public DateTime DateUpdated { get; set; }
        [Display(Name = "Người đăng")]
        public int UserProfileUserId { get; set; }
        public virtual UserProfile UserProfiles { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        [Display(Name = "Tag")]
        public virtual ICollection<Tag> Tags { get; set; }
    }
}

BaoCaoCuoiKi/Project/BaoCao/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BaoCao.Models;

namespace BaoCao.Controllers
{
    public class CommentController : Controller
    {
        private HabitBdContext db = new HabitBdContext();

        //
        // GET: /Comment/

        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.Posts);
            return View(comments.ToList());
        }

        //
        // GET: /Comment/Details/5

        public ActionResult Details(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // GET: /Comment/Create

        public ActionResult Create()
        {
            ViewBag.PostId = new SelectList(db.Posts, "ID", "Title");
            return View();
        }

        //
        // POST: /Comment/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Comment comment, int post)
        {
            if (ModelState.IsValid)
            {
                comment.PostId = post;
                comment.DateCreated = DateTime.Now;
                comment.DateUpdated = comment.DateCreated;
                db.Comments.Add(comment);
                db.SaveChanges();
                return PartialView("viewComment", comment);
                //return RedirectToAction("Index");
            }

            ViewBag.PostId = new SelectList(db.Posts, "ID", "Title", comment.PostId);
            return null;
        }

        //
        // GET: /Comment/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.PostId = new SelectList(db.Posts, "ID", "Title", comment.PostId);
            return View(comment);
        }

        //
        // POST: /Comment/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.PostId = comment.PostId;
                comment.DateCreated = comment.DateCreated;
                comment.DateUpdated = DateTime.Now;
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PostId = new SelectList(db.Posts, "ID", "Title", comment.PostId);
            return View(comment);
        }

        //
        // GET: /Comment/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // POST: /Comment/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BaoCaoCuoiKi/Project/BaoCao/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BaoCao.Models;

namespace BaoCao.Controllers
{
    public class PostController : Controller
    {
        private HabitBdContext db = new HabitBdContext();

        //
        // GET: /Post/
        [AllowAnonymous]
        public ActionResult Index()
        {
            var posts = db.Posts.Include(p => p.UserProfiles);
            return View(posts.ToList());
        }

        //
        // GET: /Post/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            ViewData["post"] = id;
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // GET: /Post/Create

        public ActionResult Create()
        {
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /Post/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Post post, string Content)
        {
            if (ModelState.IsValid)
            {
                post.DateCreated = DateTime.Now;
                post.DateUpdated = post.DateCreated;
                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName }).
                        Where(y => y.UserName == User.Identity.Name).Single().UserId;
                post.UserProfileUserId = userid;
                List<Tag> Tags = new List<Tag>();
                string[] TagContent = Content.Split(',');
                foreach (string item in TagContent)
                {
                    Tag tagExits = null;
                    var Listtag = db.Tags.Where(y => y.Content.Equals(item));
                    if (Listtag.Count() > 0)
                    {
                        tagExits = Listtag.First();
                        tagExits.Posts.Add(post);
                    }
                    else
                    {
                        tagExits = new Tag();
                        tagExits.Content = item;
                        tagExits.Posts = new List<Post>();
                        tagExits.Posts.Add(post);
                    }
                    Tags.Add(tagExits);
                }
                post.Tags = Tags;
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            return View(post);
        }

        //
        // GET: /Post/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            return View(post);
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                post.DateCreated = post.DateCreated;
                post.DateUpdated = DateTime.Now;
                post.UserProfileUserId = post.UserProfileUserId;
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            return View(post);
        }

        //
        // GET: /Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult _ViewTaginPost(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            return View(tag);
        }
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BaoCaoCuoiKi/Project/BaoCao/Views/Post/Create.cshtml
@model BaoCao.Models.Post

@{
    ViewBag.Title = "Thêm đề tài";
}

<h2>Tạo</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Đề tài</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        <div class="editor-label">
            Tag:
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => new BaoCao.Models.Tag().Content)
            @Html.ValidationMessageFor(model => new BaoCao.Models.Tag().Content)
        </div>


        <p>
            <input type="submit" value="Đăng" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Trở về danh sách", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BaoCaoCuoiKi/Project/BaoCao/Views/Post/Delete.cshtml
@model BaoCao.Models.Post

@{
    ViewBag.Title = "Xóa";
}

<h2>Xóa</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Bài đăng</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Body)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Body)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.DateCreated)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateCreated)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.DateUpdated)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateUpdated)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.UserProfiles.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfiles.UserName)
    </div>
</fieldset>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Xóa" /> |
        @Html.ActionLink("Trở về danh sách", "Index")
    </p>
}

BaoCaoCuoiKi/Project/BaoCao/Views/Post/Details.cshtml
@model BaoCao.Models.Post

@{
    ViewBag.Title = "Chi tiết";
}

<fieldset>
    <div class="display-field">
        <b>Người đăng:</b> @Html.DisplayFor(model => model.UserProfiles.UserName)
    </div>
    <div class="display-field">
        <b>@Html.DisplayNameFor(model => model.Body):</b> @Html.DisplayFor(model => model.Body)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateUpdated)
    </div>
    <p>
        @Html.ActionLink("Sửa", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Trở về danh sách", "Index")
    </p>

    @Html.Partial("_addComment", new BaoCao.Models.Comment(), ViewData)
    <div id="result">
        @foreach (var comment in Model.Comments.OrderByDescending(x => x.DateUpdated).Take(10))
        {
            <div class="display-field">
                <b>@Html.DisplayFor(x => comment.Author)</b>
            </div>
            <div class="display-field">
                @Html.DisplayFor(x => comment.Body)
            </div>
            <div class="display-field">
                <b>Cách đây:</b> @Html.DisplayFor(x => comment.LastTime)
            </div>
            <td>
                <a href="http://localhost:1621/Comment/Edit/@comment.Id">Sửa</a>
                @Html.ActionLink("Sửa", "Edit", new { id = comment.Id, postid = comment.PostId }) |
                @Html.ActionLink("Details", "Details", new { id = comment.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = comment.Id })
            </td>
            <div class="display-field"></div>
        }
    </div>
    <div class="display-field"></div>
    <div class="display-label">
        <b>Liên quan:</b>
        @foreach (var tag in Model.Tags)
        {
            @Html.ActionLink(tag.Content, "_ViewTaginPost/" + tag.ID, "Post")
        }
    </div>
</fieldset>

BaoCaoCuoiKi/Project/BaoCao/Views/Post/Edit.cshtml
@model BaoCao.Models.Post

@{
    ViewBag.Title = "Sửa";
}

<h2>Sửa</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Bài đăng</legend>

        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.DateUpdated)
        @Html.HiddenFor(model => model.DateCreated)
        @Html.HiddenFor(model => model.UserProfileUserId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        <p>
            <input type="submit" value="Lưu" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Trở về danh sách", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BaoCaoCuoiKi/Project/BaoCao/Views/Post/Index.cshtml
@model IEnumerable<BaoCao.Models.Post>

@{
    ViewBag.Title = "Diễn đàn";
}

<h2>Diễn đàn</h2>

<p>
    @Html.ActionLink("Thêm đề tài", "Create")
</p>
<style>
    table, th, td {
        border: 0px solid blue;
        border-collapse: collapse;
    }
</style>
<table>
    <tr>
        <th width=" 100"></th>
        <th width=" 300">Nội dung</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td width="100">
                <b>@Html.DisplayFor(modelItem => item.UserProfiles.UserName):</b>
            </td>
            <td width="300">
                @Html.DisplayFor(modelItem => item.Body)
            </td>

            <td width="150">
                @Html.ActionLink("Sửa", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Chi tiết", "Details", new { id = item.ID }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.ID })
            </td>
        </tr>
    }
</table>

BaoCaoCuoiKi/Project/BaoCao/Views/Post/_ViewTaginPost.cshtml
@model BaoCao.Models.Tag
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Liên quan</title>
</head>
<body>
    <div>
        <table>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => new BaoCao.Models.Post().Body)
                </th>
                <th>
                    @Html.DisplayNameFor(model => new BaoCao.Models.Post().DateCreated)
                </th>
                <th>
                    @Html.DisplayNameFor(model => new BaoCao.Models.Post().DateUpdated)
                </th>
                <th>
                    @Html.DisplayNameFor(model => new BaoCao.Models.Post().UserProfiles.UserName)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.Posts)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Body)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateCreated)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateUpdated)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserProfiles.UserName)
                    </td>
                    <td>
                        @Html.ActionLink("Sửa", "Edit", new { id = item.ID }) |
                        @Html.ActionLink("Chi tiết", "Details", new { id = item.ID }) |
                        @Html.ActionLink("Xóa", "Delete", new { id = item.ID })
                    </td>
                </tr>
            }

        </table>
    </div>
</body>
</html>

BaoCaoCuoiKi/Project/BaoCao/Views/Post/_addComment.cshtml
@model BaoCao.Models.Comment
@using (Html.BeginForm("Create", "Comment", FormMethod.Post, new { id = "my-form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="editor-label">
        @Html.LabelFor(model => model.Author)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Author)
        @Html.ValidationMessageFor(model => model.Author)
    </div>
    <div class="editor-label">
        @Html.LabelFor(model => model.Body)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Body)
        @Html.ValidationMessageFor(model => model.Body)
    </div>
    @Html.Hidden("post", ViewData["post"])
    <p>
        <input type="submit" value="Bình luận" />
    </p>
}